### ISSUE TITLE
Avahi code doesn't compile

### ISSUE THREAD

**Issue by Strahinja** [gnustep/libs-base#355]
I'm trying to get GNUstep working on Alpine Linux v3.18, and `libs-base` gives the following error when using default zeroconf API (Avahi):

```
 Compiling file GSAvahiRunLoopIntegration.m ...
GSAvahiRunLoopIntegration.m:401:3: warning: local declaration of 'poll' hides instance variable [-Wshadow-ivar]
  401 |   poll = malloc(sizeof(AvahiPoll));
      |   ^
GSAvahiRunLoopIntegration.m:401:8: error: non-object type 'int (struct pollfd *, nfds_t, int)' (aka 'int (struct pollfd *, unsigned long, int)') is not assignable
  401 |   poll = malloc(sizeof(AvahiPoll));
      |   ~~~~ ^
GSAvahiRunLoopIntegration.m:402:12: warning: local declaration of 'poll' hides instance variable [-Wshadow-ivar]
  402 |   NSAssert(poll, @"Could not allocate avahi polling structure.");
      |            ^
GSAvahiRunLoopIntegration.m:403:3: warning: local declaration of 'poll' hides instance variable [-Wshadow-ivar]
  403 |   poll->userdata = (void*)self; //userInfo
      |   ^
GSAvahiRunLoopIntegration.m:403:7: error: member reference base type 'int (struct pollfd *, nfds_t, int)' (aka 'int (struct pollfd *, unsigned long, int)') is not a structure or union
  403 |   poll->userdata = (void*)self; //userInfo
      |   ~~~~^ ~~~~~~~~
GSAvahiRunLoopIntegration.m:404:3: warning: local declaration of 'poll' hides instance variable [-Wshadow-ivar]
  404 |   poll->watch_new = GSAvahiWatchNew; //create a new GSAvahiWatcher
      |   ^

```
and so on. I assume this has to do with selecting libobjc2 (`ng-gnu-gnu`) and gnustep 2.0 ABI in `tools-make`.

Clang reports the following:
```
$ clang --version
Alpine clang version 16.0.6
Target: x86_64-alpine-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```

`libobjc*` on my system:
```
$ find /usr -name 'libobjc*' 2>/dev/null
/usr/local/lib/pkgconfig/libobjc.pc
/usr/local/lib/libobjc.so.4.6
/usr/local/lib/libobjc.so
```

The commands I used to configure various parts up to that point were:

```
#!/bin/sh
# mk-tools-make.sh
./configure --with-library-combo=ng --with-runtime-abi=gnustep-2.0 && make
```

```
#!/bin/sh
# mk-libobjc2.sh
OBJC=clang
CC=clang
CPP="clang -E"
OBJCXX=clang++
CXX=clang++

export OBJC CC CPP OBJCXX CXX

if [ -e Build ]; then
	rm -fr Build
fi
mkdir Build
cd Build
cmake .. && make
```

[Void Linux `va_copy` patch](https://github.com/void-linux/void-packages/blob/master/srcpkgs/gnustep-base/patches/use-va_copy.patch), then:
```
#!/bin/sh
# mk-libs-base.sh
OBJC=clang
CC=clang
CPP="clang -E"
OBJCXX=clang++
CXX=clang++
ICONV=gnu-iconv
LIBS="-lobjc"

export OBJC CC CPP OBJCXX CXX ICONV
export OBJCFLAGS OBJCXXFLAGS LIBS

./configure && make
```

**Comment by Strahinja** [comment]
That fixed the compilation, thanks!
